### ISSUE TITLE
Burn event can be expressed as a transfer to null

### ISSUE THREAD

**Issue by IsaacPayne** [BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts#5]
If we're expressing minting as a transfer from a null address `Transfer(address(0x0), msg.sender, tokenTotalAmount);` we should express burning as a transfer to a null address `Transfer(msg.sender, address(0x0), _value);`

https://github.com/BlockchainLabsNZ/KyberNetwork-TokenDistributionContracts/blob/master/TokenSale/contracts/KyberNetworkCrystal.sol#L56

**Comment by yaronvel** [comment]
We can consider it.
Note however that unlike minting, it will cause some inconsistency with `balanceOf`.
In particular `balanceOf` of address 0 will return 0, despite having `Transfer` event saying it has funds.
The same inconsistency is not applicable for minting.

In any case, we would like to hear your recommendation on this. We do not have a strong opinion here.

**Comment by Janther** [comment]
Hi @yarnovel,
We got the inspiration from [MiniMeToken](https://github.com/Giveth/minime/blob/master/contracts/MiniMeToken.sol#L431) for this particular behaviour. We prefer it as the transaction is properly logged into scanners which are ERC20 compatible (and can be easily reviewed and audited).

Minting and Burning are not ERC20 so MiniMeToken uses `0x0` as the minter or burner address since virtually means that once Tokens are there, they are out of the market.

The only benefit here is scanners.

Here is an example of how etherscan.io logs SNT minting.

https://etherscan.io/token/StatusNetwork?a=0x0000000000000000000000000000000000000000

**Comment by yaronvel** [comment]
Thanks. We will log it also as transfer to 0.

**Comment by OperationNine** [comment]
- [x] Fixed [346d0909](https://github.com/KyberNetwork/TokenDistributionContracts/commit/346d09096f3c8f461e368510fef95bdd76f32269)

**Comment by OperationNine** [comment]
- [x] Fixed [346d0909](https://github.com/KyberNetwork/TokenDistributionContracts/commit/346d09096f3c8f461e368510fef95bdd76f32269)
